Disable spell check for Go code
It should not spell check variable names, this is just too annoying.

(...Spell check...)
Error: snapshot/dbi.go:8:26 ... 33, Error - `csproto` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:28:25 ... 33, Error - `reallocs` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:117:44 ... 51, Error - `varints` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi_test.go:36:2 ... 8, Error - `pbdata` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi_test.go:88:55 ... 63, Error - `Mentries` is not a recognized word. (unrecognized-spelling)
Error: snapshot/doc.go:4:40 ... 55, Error - `deserialisation` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/compat_test.go:1:9 ... 21, Error - `gogosnapshot` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/compat_test.go:15:2 ... 6, Error - `popr` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:1005:2 ... 6, Error - `tmps` is not a recognized word. (unrecognized-spelling)
Error: syncer/receiver/receiver.go:11:47 ... 53, Error - `climit` is not a recognized word. (unrecognized-spelling)
Error: syncer/sync_test.go:163:38 ... 44, Error - `dbimsg` is not a recognized word. (unrecognized-spelling)
Error: syncer/utils.go:100:28 ... 40, Error - `optimisation` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:122:13 ... 20, Error - `csproto` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:122:57 ... 64, Error - `csproto` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:123:13 ... 20, Error - `csproto` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi.go:127:13 ... 20, Error - `csproto` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi_test.go:38:27 ... 33, Error - `pbdata` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi_test.go:43:24 ... 30, Error - `pbdata` is not a recognized word. (unrecognized-spelling)
Error: snapshot/dbi_test.go:106:55 ... 63, Error - `Mentries` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/compat_test.go:16:31 ... 35, Error - `popr` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/regenerate.go:1:9 ... 21, Error - `gogosnapshot` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:4:9 ... 21, Error - `gogosnapshot` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:321:34 ... 46, Error - `gogosnapshot` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:322:35 ... 47, Error - `gogosnapshot` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:1007:3 ... 7, Error - `tmps` is not a recognized word. (unrecognized-spelling)
Error: snapshot/gogosnapshot/snapshot.pb.go:1009:16 ... 20, Error - `tmps` is not a recognized word. (unrecognized-spelling)
Error: snapshot/load.go:21:52 ... 60, Error - `reallocs` is not a recognized word. (unrecognized-spelling)
Error: snapshot/load.go:49:52 ... 60, Error - `reallocs` is not a recognized word. (unrecognized-spelling)
Error: snapshot/load_test.go:33:45 ... 53, Error - `Mentries` is not a recognized word. (unrecognized-spelling)
Error: syncer/receiver/receiver.go:36:30 ... 36, Error - `climit` is not a recognized word. (unrecognized-spelling)
Error: syncer/receiver/receiver.go:41:26 ... 32, Error - `climit` is not a recognized word. (unrecognized-spelling)
Error: syncer/receiver/receiver.go:79:29 ... 35, Error - `climit` is not a recognized word. (unrecognized-spelling)
Error: syncer/receiver/receiver.go:80:29 ... 35, Error - `climit` is not a recognized word. (unrecognized-spelling)
Error: syncer/utils.go:116:37 ... 45, Error - `reallocs` is not a recognized word. (unrecognized-spelling)
(...Compare expect with new output...)